CREATE TABLE IF NOT EXISTS course_visits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_title VARCHAR(255),
    course_code VARCHAR(50),
    awarding_body VARCHAR(255),
    visit_type VARCHAR(120),
    visit_date DATE,
    lead_contact_awarding_body VARCHAR(255),
    college_visit_coordinator VARCHAR(255),
    version VARCHAR(20) DEFAULT '1.0',
    last_updated_date DATE,
    purpose_of_visit TEXT,
    scope_focus_areas TEXT,
    key_standards_regulations TEXT,
    visit_agenda TEXT,
    required_attendees TEXT,
    pre_visit_preparation TEXT,
    evidence_document_log TEXT,
    day_of_visit_management TEXT,
    post_visit_actions TEXT,
    risk_issue_log TEXT,
    signoff_details TEXT,
    overall_status VARCHAR(50) DEFAULT 'Draft',
    completion_percentage INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_course (course_title),
    KEY idx_course_code (course_code),
    KEY idx_status (overall_status),
    KEY idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
