-- Import courses scraped from sclondon.co.uk
-- Match by course_title and update, otherwise insert
UPDATE courses SET course_code = 'SCL-BSC-HONS-BUSINESS-MANAGEMENT-OFFERED-WITH-FOU', course_type = 'Degree', duration_months = NULL, description = 'Why Study Business Management with Foundation Year? &nbsp; Our course will introduce you to different organisations and external environments, so you can understand how they operate and managed as businesses. It is practical in nature, which allows you to begin building your know', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 1, blended_available = 0, course_status = 'active' WHERE course_title = 'BSC (Hons) Business Management offered with Foundation Year';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-BSC-HONS-BUSINESS-MANAGEMENT-OFFERED-WITH-FOU', 'BSC (Hons) Business Management offered with Foundation Year', 'Degree', NULL, 'Why Study Business Management with Foundation Year? &nbsp; Our course will introduce you to different organisations and external environments, so you can understand how they operate and managed as businesses. It is practical in nature, which allows you to begin building your know', NULL, 0, 0, 1, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'BSC (Hons) Business Management offered with Foundation Year');

UPDATE courses SET course_code = 'SCL-BTEC-HIGHER-NATIONAL-CERTIFICATE-1-YEAR', course_type = 'HND', duration_months = 12, description = 'The HNC is a level 4 qualification delivered over 1 year. The HNC is an embedded component of the HND, however, it can be taken as a stand- alone qualification. If a student opts to take the HNC they would be eligible to gain a National Certificate after successful completion of ', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'BTEC Higher National Certificate (1 Year)';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-BTEC-HIGHER-NATIONAL-CERTIFICATE-1-YEAR', 'BTEC Higher National Certificate (1 Year)', 'HND', 12, 'The HNC is a level 4 qualification delivered over 1 year. The HNC is an embedded component of the HND, however, it can be taken as a stand- alone qualification. If a student opts to take the HNC they would be eligible to gain a National Certificate after successful completion of ', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'BTEC Higher National Certificate (1 Year)');

UPDATE courses SET course_code = 'SCL-BTEC-HIGHER-NATIONAL-DIPLOMA-2-YEARS', course_type = 'HND', duration_months = 24, description = 'The HND is a level 5 qualification delivered over 2 years, the first year at level 4 and the second year at level 5. If a student opts to take the HND they would be eligible to gain a Higher National Diploma after successful completion of a minimum of 16 units.The Higher National', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'BTEC Higher National Diploma (2 Years)';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-BTEC-HIGHER-NATIONAL-DIPLOMA-2-YEARS', 'BTEC Higher National Diploma (2 Years)', 'HND', 24, 'The HND is a level 5 qualification delivered over 2 years, the first year at level 4 and the second year at level 5. If a student opts to take the HND they would be eligible to gain a Higher National Diploma after successful completion of a minimum of 16 units.The Higher National', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'BTEC Higher National Diploma (2 Years)');

UPDATE courses SET course_code = 'SCL-EXTENDED-DIPLOMA-IN-STRATEGIC-MANAGEMENT-AND', course_type = 'Degree', duration_months = NULL, description = 'Edexcel is the UK?s largest awarding body, offering academic and vocational qualifications to more than 25,000 schools, colleges, employers and other places of learning in the UK and in over 100 countries worldwide. Edexcel qualifications are recognised by employers and higher ed', awarding_body = ', offering academic and vocational qualifications to more than 25,000 schools, colleges, employers a', full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'Extended Diploma In Strategic Management and leadership (QCF) Edexcel Level 7';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-EXTENDED-DIPLOMA-IN-STRATEGIC-MANAGEMENT-AND', 'Extended Diploma In Strategic Management and leadership (QCF) Edexcel Level 7', 'Degree', NULL, 'Edexcel is the UK?s largest awarding body, offering academic and vocational qualifications to more than 25,000 schools, colleges, employers and other places of learning in the UK and in over 100 countries worldwide. Edexcel qualifications are recognised by employers and higher ed', ', offering academic and vocational qualifications to more than 25,000 schools, colleges, employers a', 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'Extended Diploma In Strategic Management and leadership (QCF) Edexcel Level 7');

UPDATE courses SET course_code = 'SCL-GCSE-GCE-A-LEVEL-COURSES', course_type = 'Vocational', duration_months = NULL, description = '&nbsp; STRATFORD TUITION CENTRE &nbsp; Private Tutoring &nbsp; Our private tutoring program provides students the personal attention and focus their need for academic success in core subjects. In private (one-to-one) or small group sessions, our experienced tutors coach each stud', awarding_body = ', recognized in the field of education as a highly professional and responsive organization, committ', full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'GCSE / GCE ? A LEVEL COURSES';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-GCSE-GCE-A-LEVEL-COURSES', 'GCSE / GCE ? A LEVEL COURSES', 'Vocational', NULL, '&nbsp; STRATFORD TUITION CENTRE &nbsp; Private Tutoring &nbsp; Our private tutoring program provides students the personal attention and focus their need for academic success in core subjects. In private (one-to-one) or small group sessions, our experienced tutors coach each stud', ', recognized in the field of education as a highly professional and responsive organization, committ', 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'GCSE / GCE ? A LEVEL COURSES');

UPDATE courses SET course_code = 'SCL-HIGHER-NATIONAL-DIPLOMA-IN-INTERNATIONAL-TRAV', course_type = 'HND', duration_months = 24, description = 'Pearson BTEC HND (Level 4/5) Awarding Body: Pearson Education Mode: Full time Duration: 2 Years Stratford College London Academic Board recommends this programme specification. However, this specification is designed in relation to the UK Quality Code for Higher Education, making', awarding_body = 'Pearson Education Mode: Full time Duration: 2 Years Stratford College London Academic Board recommen', full_time_available = 1, part_time_available = 1, online_available = 1, blended_available = 0, course_status = 'active' WHERE course_title = 'Higher National Diploma in International Travel &amp; Tourism Management';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-HIGHER-NATIONAL-DIPLOMA-IN-INTERNATIONAL-TRAV', 'Higher National Diploma in International Travel &amp; Tourism Management', 'HND', 24, 'Pearson BTEC HND (Level 4/5) Awarding Body: Pearson Education Mode: Full time Duration: 2 Years Stratford College London Academic Board recommends this programme specification. However, this specification is designed in relation to the UK Quality Code for Higher Education, making', 'Pearson Education Mode: Full time Duration: 2 Years Stratford College London Academic Board recommen', 1, 1, 1, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'Higher National Diploma in International Travel &amp; Tourism Management');

UPDATE courses SET course_code = 'SCL-HNC-HND-ADMINISTRATION-AND-INFORMATION-TECHNO', course_type = 'HND', duration_months = NULL, description = 'The HNC and HND in Administration and Information Technology provide candidates with a progression route into employment in a general administrative role in small to medium enterprises. It also provides opportunities to develop the skills and knowledge required for more specialis', awarding_body = 'Scottish Qualification Authority (SQA) Who does this qualification suit? The HN', full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'HNC/HND Administration and Information Technology (SQA)';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-HNC-HND-ADMINISTRATION-AND-INFORMATION-TECHNO', 'HNC/HND Administration and Information Technology (SQA)', 'HND', NULL, 'The HNC and HND in Administration and Information Technology provide candidates with a progression route into employment in a general administrative role in small to medium enterprises. It also provides opportunities to develop the skills and knowledge required for more specialis', 'Scottish Qualification Authority (SQA) Who does this qualification suit? The HN', 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'HNC/HND Administration and Information Technology (SQA)');

UPDATE courses SET course_code = 'SCL-HND-HOSPITALITY-MANAGEMENT', course_type = 'HND', duration_months = NULL, description = 'The Higher National Diploma in Hospitality Management (HND) is a vocational course. This means that not only do you learn the theoretical aspects but it also provides you with ability to relate this to the real world of work. Evaluating the application of these theories and conce', awarding_body = NULL, full_time_available = 1, part_time_available = 1, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'HND HOSPITALITY MANAGEMENT';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-HND-HOSPITALITY-MANAGEMENT', 'HND HOSPITALITY MANAGEMENT', 'HND', NULL, 'The Higher National Diploma in Hospitality Management (HND) is a vocational course. This means that not only do you learn the theoretical aspects but it also provides you with ability to relate this to the real world of work. Evaluating the application of these theories and conce', NULL, 1, 1, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'HND HOSPITALITY MANAGEMENT');

UPDATE courses SET course_code = 'SCL-HND-IN-BUSINESS-RQF', course_type = 'HND', duration_months = 24, description = 'Pearson BTEC Level 5 Higher National Diploma in Business (Business Management) (RQF) Course ID --> Course Name ECLHNBM04-RQF --> Pearson BTEC Level 5 Higher National Diploma in Business (Business Management) (RQF) &nbsp; Awarding Body: Pearson Duration: 24 Months RQF Level: 5 Cre', awarding_body = 'Pearson Duration: 24 Months RQF Level: 5 Credit Value: 240 Credits Minimum Fees: Student Finance is', full_time_available = 1, part_time_available = 1, online_available = 1, blended_available = 1, course_status = 'active' WHERE course_title = 'HND IN BUSINESS RQF';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-HND-IN-BUSINESS-RQF', 'HND IN BUSINESS RQF', 'HND', 24, 'Pearson BTEC Level 5 Higher National Diploma in Business (Business Management) (RQF) Course ID --> Course Name ECLHNBM04-RQF --> Pearson BTEC Level 5 Higher National Diploma in Business (Business Management) (RQF) &nbsp; Awarding Body: Pearson Duration: 24 Months RQF Level: 5 Cre', 'Pearson Duration: 24 Months RQF Level: 5 Credit Value: 240 Credits Minimum Fees: Student Finance is', 1, 1, 1, 1, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'HND IN BUSINESS RQF');

UPDATE courses SET course_code = 'SCL-HND-IN-HOSPITALITY-MANAGEMENT', course_type = 'HND', duration_months = 24, description = 'Purpose of the BTEC Higher Nationals in Hospitality Management The purpose of BTEC Higher Nationals in Hospitality Management is to develop students as professional, self-reflecting individuals able to meet the demands of employers in Hospitality Management and adapt to a constan', awarding_body = 'an approved further education institution Related work experience An interna', full_time_available = 1, part_time_available = 1, online_available = 1, blended_available = 1, course_status = 'active' WHERE course_title = 'HND in Hospitality Management';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-HND-IN-HOSPITALITY-MANAGEMENT', 'HND in Hospitality Management', 'HND', 24, 'Purpose of the BTEC Higher Nationals in Hospitality Management The purpose of BTEC Higher Nationals in Hospitality Management is to develop students as professional, self-reflecting individuals able to meet the demands of employers in Hospitality Management and adapt to a constan', 'an approved further education institution Related work experience An interna', 1, 1, 1, 1, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'HND in Hospitality Management');

UPDATE courses SET course_code = 'SCL-HND-IN-LEADERSHIP-AND-MANAGEMENT-FOR-ENGLAND', course_type = 'HND', duration_months = 24, description = 'Introduction &nbsp; Pearson awards are work-related qualifications for students taking their first steps into employment, or for those already in employment and seeking career development opportunities. Such awards provide progression into the workplace either directly or via stu', awarding_body = 'Pearson Duration: 24 Months RQF Level: 5 Credit Value: 240 Credits Minimum Fees: Student Finance is', full_time_available = 1, part_time_available = 1, online_available = 1, blended_available = 1, course_status = 'active' WHERE course_title = 'HND in Leadership and Management for England Course';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-HND-IN-LEADERSHIP-AND-MANAGEMENT-FOR-ENGLAND', 'HND in Leadership and Management for England Course', 'HND', 24, 'Introduction &nbsp; Pearson awards are work-related qualifications for students taking their first steps into employment, or for those already in employment and seeking career development opportunities. Such awards provide progression into the workplace either directly or via stu', 'Pearson Duration: 24 Months RQF Level: 5 Credit Value: 240 Credits Minimum Fees: Student Finance is', 1, 1, 1, 1, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'HND in Leadership and Management for England Course');

UPDATE courses SET course_code = 'SCL-NCFE-8211-QUALIFICATIONS', course_type = 'Vocational', duration_months = NULL, description = 'NCFE is the UK?s longest established awarding body, recognized in the field of education as a highly professional and responsive organization, committed to maintaining excellent customer service and a friendly approach. &nbsp; *Course commencement ? Subject to number of student a', awarding_body = ', recognized in the field of education as a highly professional and responsive organization, committ', full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE &#8211; QUALIFICATIONS';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-8211-QUALIFICATIONS', 'NCFE &#8211; QUALIFICATIONS', 'Vocational', NULL, 'NCFE is the UK?s longest established awarding body, recognized in the field of education as a highly professional and responsive organization, committed to maintaining excellent customer service and a friendly approach. &nbsp; *Course commencement ? Subject to number of student a', ', recognized in the field of education as a highly professional and responsive organization, committ', 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE &#8211; QUALIFICATIONS');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-1-AWARD-IN-TRAVEL-038-TOURISM', course_type = 'Vocational', duration_months = NULL, description = '&nbsp; Introduction &nbsp; These qualifications aim to: provide learners with an understanding of the basic principles of the travel and tourism industry and allows them to explore the various avenues of work within this industry. allow learners to gain transferrable skills that ', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 1 ? Award in Travel &#038; Tourism';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-1-AWARD-IN-TRAVEL-038-TOURISM', 'NCFE Level 1 ? Award in Travel &#038; Tourism', 'Vocational', NULL, '&nbsp; Introduction &nbsp; These qualifications aim to: provide learners with an understanding of the basic principles of the travel and tourism industry and allows them to explore the various avenues of work within this industry. allow learners to gain transferrable skills that ', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 1 ? Award in Travel &#038; Tourism');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-1-CERTIFICATE-IN-HOSPITALITY-038-C', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; The Level 1 Certificate in Hospitality &amp; Catering is a joint development between NCFE and Network Training Publishing. The Level 1 Certificate in Hospitality &amp; Catering is suitable as an introduction for people who wish to access training in Hospitalit', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 1 ? Certificate in Hospitality &#038; Catering Management';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-1-CERTIFICATE-IN-HOSPITALITY-038-C', 'NCFE Level 1 ? Certificate in Hospitality &#038; Catering Management', 'Vocational', NULL, 'Introduction &nbsp; The Level 1 Certificate in Hospitality &amp; Catering is a joint development between NCFE and Network Training Publishing. The Level 1 Certificate in Hospitality &amp; Catering is suitable as an introduction for people who wish to access training in Hospitalit', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 1 ? Certificate in Hospitality &#038; Catering Management');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-1-CERTIFICATE-IN-TRAVEL-AND-TOURIS', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; These qualifications aim to: provide learners with an understanding of the basic principles of the travel and tourism industry and allows them to explore the various avenues of work within this industry. allow learners to gain transferrable skills that can be ', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 1 Certificate in Travel and Tourism';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-1-CERTIFICATE-IN-TRAVEL-AND-TOURIS', 'NCFE Level 1 Certificate in Travel and Tourism', 'Vocational', NULL, 'Introduction &nbsp; These qualifications aim to: provide learners with an understanding of the basic principles of the travel and tourism industry and allows them to explore the various avenues of work within this industry. allow learners to gain transferrable skills that can be ', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 1 Certificate in Travel and Tourism');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-CERTIFICATE-FOR-AIRLINE-CABIN-CR', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; The Level 2 Certificate in Cabin Crew prepares learners for entry to airline industry training. It is not intended as a replacement to the training given by airlines upon the receuirement of new cabin crew staff. This qualifications provides the basic backgrou', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 ? Certificate for Airline Cabin Crew';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-CERTIFICATE-FOR-AIRLINE-CABIN-CR', 'NCFE Level 2 ? Certificate for Airline Cabin Crew', 'Vocational', NULL, 'Introduction &nbsp; The Level 2 Certificate in Cabin Crew prepares learners for entry to airline industry training. It is not intended as a replacement to the training given by airlines upon the receuirement of new cabin crew staff. This qualifications provides the basic backgrou', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 ? Certificate for Airline Cabin Crew');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-AWARD-FOR-RESORT-REPRESENTATIVES', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; This qualification aims to: &nbsp; &#x2666; provide skills and knowledge required to work effectively as a Resort Representative &#x2666; provide Resort Representatives with the tools to deliver the highest level of standards and service &#x2666; enhance the s', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 Award for Resort Representatives';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-AWARD-FOR-RESORT-REPRESENTATIVES', 'NCFE Level 2 Award for Resort Representatives', 'Vocational', NULL, 'Introduction &nbsp; This qualification aims to: &nbsp; &#x2666; provide skills and knowledge required to work effectively as a Resort Representative &#x2666; provide Resort Representatives with the tools to deliver the highest level of standards and service &#x2666; enhance the s', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 Award for Resort Representatives');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-AWARD-IN-FOOD-SAFETY-IN-CATERING', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; The NCFE Level 2 Award in Food Safety in Catering focuses on the importance of hygiene, the food handler?s legal responsibilities and their role in monitoring food safety procedures, and how to handle, prepare and process food safely. The objectives of the qua', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 Award in Food Safety in Catering';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-AWARD-IN-FOOD-SAFETY-IN-CATERING', 'NCFE Level 2 Award in Food Safety in Catering', 'Vocational', NULL, 'Introduction &nbsp; The NCFE Level 2 Award in Food Safety in Catering focuses on the importance of hygiene, the food handler?s legal responsibilities and their role in monitoring food safety procedures, and how to handle, prepare and process food safely. The objectives of the qua', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 Award in Food Safety in Catering');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-AVIATION-OPERATIO', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; This qualification is designed for learners interested in aviation operations. This qualification aims to: &#x2666; provide learners with skills in health, safety, security and communications required to work within an Aviation Environment &#x2666; develop lea', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 Certificate in Aviation Operations on the Ground (Knowledge)';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-AVIATION-OPERATIO', 'NCFE Level 2 Certificate in Aviation Operations on the Ground (Knowledge)', 'Vocational', NULL, 'Introduction &nbsp; This qualification is designed for learners interested in aviation operations. This qualification aims to: &#x2666; provide learners with skills in health, safety, security and communications required to work within an Aviation Environment &#x2666; develop lea', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 Certificate in Aviation Operations on the Ground (Knowledge)');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-HOSPITALITY-AND-C', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; Learners will develop the underpinning skills, knowledge and understanding required to work in the hospitality industry in roles such as receptionists, back office team and reservation team in a variety of different environments. The objectives of this qualifi', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 Certificate in Hospitality and Catering Principles (Front of House Reception)';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-HOSPITALITY-AND-C', 'NCFE Level 2 Certificate in Hospitality and Catering Principles (Front of House Reception)', 'Vocational', NULL, 'Introduction &nbsp; Learners will develop the underpinning skills, knowledge and understanding required to work in the hospitality industry in roles such as receptionists, back office team and reservation team in a variety of different environments. The objectives of this qualifi', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 Certificate in Hospitality and Catering Principles (Front of House Reception)');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-HOSPITALITY-AN-2', course_type = 'Vocational', duration_months = NULL, description = 'Introduction &nbsp; Help learners develop the knowledge, skills and understanding in areas such as maintaining a safe, hygienic and secure working environment, working effectively as part of a hospitality team, maintaining food safety in a catering environment and knowledge of th', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 Certificate in Hospitality and Catering Principles (Hospitality Services)';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-HOSPITALITY-AN-2', 'NCFE Level 2 Certificate in Hospitality and Catering Principles (Hospitality Services)', 'Vocational', NULL, 'Introduction &nbsp; Help learners develop the knowledge, skills and understanding in areas such as maintaining a safe, hygienic and secure working environment, working effectively as part of a hospitality team, maintaining food safety in a catering environment and knowledge of th', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 Certificate in Hospitality and Catering Principles (Hospitality Services)');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-NUTRITION-038-HEA', course_type = 'Vocational', duration_months = NULL, description = '&nbsp; Introduction The NCFE Level 2 Certificate in Nutrition and Health has been developed in response to rising levels of obesity in both adults and children. Modules: The award consists of three mandatory units: Explore principles of health eating Consider nutritional needs of', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 Certificate in Nutrition &#038; Health';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-CERTIFICATE-IN-NUTRITION-038-HEA', 'NCFE Level 2 Certificate in Nutrition &#038; Health', 'Vocational', NULL, '&nbsp; Introduction The NCFE Level 2 Certificate in Nutrition and Health has been developed in response to rising levels of obesity in both adults and children. Modules: The award consists of three mandatory units: Explore principles of health eating Consider nutritional needs of', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 Certificate in Nutrition &#038; Health');

UPDATE courses SET course_code = 'SCL-NCFE-LEVEL-2-NVQ-DIPLOMA-IN-FRONT-OF-HOUSE-RE', course_type = 'Degree', duration_months = NULL, description = 'Introduction &nbsp; This qualification is aimed at those working in, or who wish to enter, the hospitality industry. It must be assessed in the workplace or in a realistic working environment to allow learners to gain handson experience as they train. It allows flexibility in cho', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'NCFE Level 2 NVQ Diploma in Front of House Reception';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-NCFE-LEVEL-2-NVQ-DIPLOMA-IN-FRONT-OF-HOUSE-RE', 'NCFE Level 2 NVQ Diploma in Front of House Reception', 'Degree', NULL, 'Introduction &nbsp; This qualification is aimed at those working in, or who wish to enter, the hospitality industry. It must be assessed in the workplace or in a realistic working environment to allow learners to gain handson experience as they train. It allows flexibility in cho', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'NCFE Level 2 NVQ Diploma in Front of House Reception');

UPDATE courses SET course_code = 'SCL-PEARSON-BTEC-LEVEL-7-EXTENDED-DIPLOMA-IN-STRA', course_type = 'Degree', duration_months = NULL, description = 'Edexcel is the UK?s largest awarding body, offering academic and vocational qualifications to more than 25,000 schools, colleges, employers and other places of learning in the UK and in over 100 countries worldwide. Edexcel qualifications are recognised by employers and higher ed', awarding_body = ', offering academic and vocational qualifications to more than 25,000 schools, colleges, employers a', full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'Pearson BTEC Level 7 Extended Diploma in Strategic Management and Leadership';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-PEARSON-BTEC-LEVEL-7-EXTENDED-DIPLOMA-IN-STRA', 'Pearson BTEC Level 7 Extended Diploma in Strategic Management and Leadership', 'Degree', NULL, 'Edexcel is the UK?s largest awarding body, offering academic and vocational qualifications to more than 25,000 schools, colleges, employers and other places of learning in the UK and in over 100 countries worldwide. Edexcel qualifications are recognised by employers and higher ed', ', offering academic and vocational qualifications to more than 25,000 schools, colleges, employers a', 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'Pearson BTEC Level 7 Extended Diploma in Strategic Management and Leadership');

UPDATE courses SET course_code = 'SCL-STRUCTURE-OF-EDEXCEL-LEVEL-5-BTEC-HIGHER-NATI', course_type = 'HND', duration_months = NULL, description = 'Structure of Edexcel L evel 5 BTEC H igher National Diploma in Hospitality Management &nbsp; Unit number &nbsp; &nbsp; Core units ? all seven units mu st be taken &nbsp; Unit l evel H1 or H 2 &nbsp; 1 &nbsp; The Contemporary Hospitality Industry &nbsp; H2 &nbsp; 2 &nbsp; The Deve', awarding_body = NULL, full_time_available = 0, part_time_available = 0, online_available = 0, blended_available = 0, course_status = 'active' WHERE course_title = 'Structure of Edexcel Level 5 BTEC Higher National Diploma in Hospitality Management';
INSERT INTO courses (course_code, course_title, course_type, duration_months, description, awarding_body, full_time_available, part_time_available, online_available, blended_available, course_status)
SELECT 'SCL-STRUCTURE-OF-EDEXCEL-LEVEL-5-BTEC-HIGHER-NATI', 'Structure of Edexcel Level 5 BTEC Higher National Diploma in Hospitality Management', 'HND', NULL, 'Structure of Edexcel L evel 5 BTEC H igher National Diploma in Hospitality Management &nbsp; Unit number &nbsp; &nbsp; Core units ? all seven units mu st be taken &nbsp; Unit l evel H1 or H 2 &nbsp; 1 &nbsp; The Contemporary Hospitality Industry &nbsp; H2 &nbsp; 2 &nbsp; The Deve', NULL, 0, 0, 0, 0, 'active'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE course_title = 'Structure of Edexcel Level 5 BTEC Higher National Diploma in Hospitality Management');

