-- Import application reviews from local database
-- 6 reviews for applications 1, 3, 4, 5, 6, 7

INSERT INTO `application_reviews` VALUES 
(1,1,1,'final_decision','suitable',1,1,NULL,'accept','{\"reviewer_name\":\"Test Reviewer\",\"review_date\":\"2026-02-07\",\"documents_verified\":\"Yes\",\"eligibility_check\":\"Meets criteria\",\"interview_conducted\":\"Yes\",\"interview_outcome\":\"Pass\",\"english_requirement_met\":\"Yes\",\"additional_notes\":\"test\",\"decision\":\"Offer\",\"reason_for_refusal\":\"\",\"detailed_comments\":\"Approved\",\"committee_chair_name\":\"Chair\",\"final_decision_date\":\"2026-02-07\",\"final_decision_confirmation\":true}',NULL,0,NULL,NULL,NULL,'2026-02-07 12:41:12'),
(2,5,1,'final_decision','suitable',0,1,NULL,'reject','{\"reviewer_name\":\"test\",\"review_date\":\"2026-02-07\",\"documents_verified\":\"Yes\",\"eligibility_check\":\"Does not meet criteria\",\"interview_conducted\":\"No\",\"interview_outcome\":\"\",\"english_requirement_met\":\"No\",\"additional_notes\":\"\",\"decision\":\"Refusal\",\"reason_for_refusal\":\"English language requirement not met\",\"detailed_comments\":\"test\",\"committee_chair_name\":\"test\",\"final_decision_date\":\"2026-02-07\",\"final_decision_confirmation\":true}',NULL,0,NULL,NULL,NULL,'2026-02-07 14:42:37'),
(3,4,1,'final_decision','suitable',1,1,NULL,'conditional_accept','{\"reviewer_name\":\"test\",\"review_date\":\"2026-02-07\",\"documents_verified\":\"Yes\",\"eligibility_check\":\"Meets criteria\",\"interview_conducted\":\"Yes\",\"interview_outcome\":\"Pass\",\"english_requirement_met\":\"Yes\",\"additional_notes\":\"test\",\"decision\":\"Conditional Offer\",\"reason_for_refusal\":\"\",\"detailed_comments\":\"test\",\"committee_chair_name\":\"test\",\"final_decision_date\":\"2026-02-07\",\"final_decision_confirmation\":true}',NULL,0,NULL,NULL,NULL,'2026-02-07 14:43:38'),
(4,3,1,'final_decision','suitable',1,1,NULL,'accept','{\"reviewer_name\":\"test\",\"review_date\":\"2026-02-07\",\"documents_verified\":\"Yes\",\"eligibility_check\":\"Meets criteria\",\"interview_conducted\":\"Yes\",\"interview_outcome\":\"Pass\",\"english_requirement_met\":\"Yes\",\"additional_notes\":\"test\",\"decision\":\"Offer\",\"reason_for_refusal\":\"\",\"detailed_comments\":\"test\",\"committee_chair_name\":\"test\",\"final_decision_date\":\"2026-02-07\",\"final_decision_confirmation\":true}',NULL,0,NULL,NULL,NULL,'2026-02-07 14:44:32'),
(5,6,1,'final_decision','suitable',1,1,NULL,'accept','{\"reviewer_name\":\"Fazli\",\"review_date\":\"2026-02-08\",\"documents_verified\":\"Yes\",\"eligibility_check\":\"Meets criteria\",\"interview_conducted\":\"Yes\",\"interview_outcome\":\"Pass\",\"english_requirement_met\":\"Yes\",\"additional_notes\":\"test\",\"decision\":\"Offer\",\"reason_for_refusal\":\"\",\"detailed_comments\":\"test offer\",\"committee_chair_name\":\"Khalid\",\"final_decision_date\":\"2026-02-08\",\"final_decision_confirmation\":true}',NULL,0,NULL,NULL,NULL,'2026-02-08 09:22:31'),
(6,7,1,'final_decision','suitable',1,1,NULL,'accept','{\"reviewer_name\":\"Asad Khan\",\"review_date\":\"2026-02-11\",\"documents_verified\":\"Yes\",\"eligibility_check\":\"Meets criteria\",\"interview_conducted\":\"Yes\",\"interview_outcome\":\"Pass\",\"english_requirement_met\":\"Yes\",\"additional_notes\":\"test\",\"decision\":\"Offer\",\"reason_for_refusal\":\"\",\"detailed_comments\":\"test\",\"committee_chair_name\":\"test\",\"final_decision_date\":\"2026-02-11\",\"final_decision_confirmation\":true}',NULL,0,NULL,NULL,NULL,'2026-02-11 15:25:16');

SELECT 'Application reviews imported successfully' as status;
SELECT COUNT(*) as total_reviews FROM application_reviews;
SELECT id, application_id, recommendation, reviewed_at FROM application_reviews;
