ALTER TABLE student_applications ADD COLUMN IF NOT EXISTS programme_type_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE student_applications ADD COLUMN IF NOT EXISTS intake_id INT DEFAULT NULL;
ALTER TABLE student_applications MODIFY COLUMN course_code VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL;
ALTER TABLE application_reviews ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE course_inductions ADD COLUMN IF NOT EXISTS course_id INT DEFAULT NULL;
ALTER TABLE course_inductions ADD COLUMN IF NOT EXISTS moodle_course_id INT DEFAULT NULL;
CREATE TABLE IF NOT EXISTS enquiries (id INT PRIMARY KEY AUTO_INCREMENT, first_name VARCHAR(100), last_name VARCHAR(100), email VARCHAR(255), phone VARCHAR(50), course_interest VARCHAR(255), message TEXT, status VARCHAR(50) DEFAULT 'new', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS application_documents (id INT PRIMARY KEY AUTO_INCREMENT, application_id INT NOT NULL, document_type VARCHAR(100), original_filename VARCHAR(255), file_path VARCHAR(500), is_deleted TINYINT(1) DEFAULT 0, upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_app_id (application_id));