#!/bin/bash

# SCL Institute Moodle Theme Installation Guide
# This guide will help you install the custom SCL theme in Moodle

echo "================================"
echo "SCL Institute Moodle Theme"
echo "Installation Guide"
echo "================================"
echo ""

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Copy theme files to Moodle installation${NC}"
echo "========================================================="
echo ""
echo "Option A: Using Docker (Recommended)"
echo ""
echo "1. Copy the theme directory:"
echo "   docker cp moodle-theme-scl scli-moodle-dev:/bitnami/moodle/theme/scl"
echo ""
echo "2. Or for production:"
echo "   docker cp moodle-theme-scl scli-moodle-prod:/bitnami/moodle/theme/scl"
echo ""

echo -e "${BLUE}Step 2: Access Moodle Administration${NC}"
echo "========================================================="
echo ""
echo "1. Login to Moodle as Administrator"
echo "2. Go to: Site administration → Appearance → Themes → Theme selector"
echo "3. Look for 'scl' theme in the available themes list"
echo ""

echo -e "${BLUE}Step 3: Activate the Theme${NC}"
echo "========================================================="
echo ""
echo "1. Click on the SCL theme"
echo "2. Click 'Select theme' button"
echo "3. Click 'Save changes'"
echo ""

echo -e "${BLUE}Step 4: Customize Theme Settings${NC}"
echo "========================================================="
echo ""
echo "Go to: Site administration → Appearance → Themes → SCL Theme"
echo ""
echo "Available customizations:"
echo "  • Background image"
echo "  • Font size"
echo "  • Font name"
echo "  • Color scheme"
echo ""

echo -e "${BLUE}Step 5: Verify Installation${NC}"
echo "========================================================="
echo ""
echo "1. Log out and refresh the login page"
echo "2. Verify the purple SCL color scheme is displayed"
echo "3. Check that all elements are styled correctly:"
echo "   ✓ Header with purple gradient"
echo "   ✓ Buttons with SCL branding"
echo "   ✓ Cards and sections with proper styling"
echo "   ✓ Responsive design on mobile devices"
echo ""

echo -e "${GREEN}Theme Installation Complete!${NC}"
echo ""
echo "Theme Features:"
echo "  ✓ Purple & Professional Design"
echo "  ✓ Responsive and Mobile-Friendly"
echo "  ✓ Accessibility Compliant"
echo "  ✓ Fast Load Times"
echo "  ✓ Dark Mode Option"
echo "  ✓ Customizable Colors & Fonts"
echo ""

echo -e "${YELLOW}Support & Troubleshooting${NC}"
echo "========================================================="
echo ""
echo "If you encounter issues:"
echo ""
echo "1. Check Moodle logs:"
echo "   docker logs scli-moodle-dev"
echo ""
echo "2. Clear Moodle cache:"
echo "   Go to Site administration → Development → Purge caches"
echo ""
echo "3. Check file permissions:"
echo "   Theme directory should be readable by Moodle"
echo ""
echo "For manual file copy:"
echo "  tar -czf moodle-theme-scl.tar.gz moodle-theme-scl/"
echo "  scp moodle-theme-scl.tar.gz user@server:/path/to/moodle/theme/"
echo "  tar -xzf moodle-theme-scl.tar.gz"
echo ""

echo -e "${BLUE}Contact Information${NC}"
echo "========================================================="
echo "For theme support: admin@sclsandbox.xyz"
echo "Documentation: http://system.sclsandbox.xyz/help"
echo ""
